# specific branch build with batching
trigger:
  batch: true
  paths:
    include:
    - deployment/arm
    - edge-solution
    - pipelines/build-ARMtemplate.yml
    - pipelines/deploy-ARMtemplate.yml

# Build after completion of Release WebApp
resources:
  pipelines:
  - pipeline: build
    project: UnifiedEdgeScenarios
    source: Release ues-app
    trigger:
      enabled: true

pool:
  vmImage: 'ubuntu-latest'

variables:
  ${{ if eq(variables['Build.SourceBranchName'], 'release') }}:
    Variable_Group: 'ARMTemplate_ReleaseEnvironment'
  ${{ if ne(variables['Build.SourceBranchName'], 'release') }}:
     Variable_Group: 'ARMTemplate_TestEnvironment'


stages:
- stage: 'Build'
  jobs:
  - job: 'Build'
    variables:
     - group: ${{variables.Variable_Group}}
    displayName: 'Build ARM Template'
    steps:
    - checkout: self

    - task: Bash@3
      displayName: 'ShellCheck validation for arm template deployment scripts'
      inputs:
        targetType: 'inline'
        script: |
          
          IS_SHELLCHECK_INSTALLED=$(apt list --installed | grep -c -w shellcheck)
          if [ "$IS_SHELLCHECK_INSTALLED" -eq 0 ]; then
              echo "Installing shellcheck"
              sudo apt-get install shellcheck
              echo "Installed shellcheck"
          fi
          
          # Change directory location to template scripts folder
          cd deployment/arm/scripts
          
          # Run shellcheck, Shellcheck will return a list of warnings if the script is not complient with all the rules
          # We are checking the result returned by shellcheck.
          SHELL_CHECK_RESULT_DISK_SETUP=$(shellcheck ./disk-setup.sh -x)
          SHELL_CHECK_RESULT_IOT_SETUP=$(shellcheck ./create-setup-iot-edge-device.sh -x)
          SHELL_CHECK_RESULT_DEPLOY_MODULES=$(shellcheck ./deploy-modules.sh -x)
          if [ -z "$SHELL_CHECK_RESULT_DISK_SETUP" ] && [ -z "$SHELL_CHECK_RESULT_IOT_SETUP" ] && [ -z "$SHELL_CHECK_RESULT_DEPLOY_MODULES" ]; then
              echo "Pass: There are no warnings from shellcheck"
          else
              if [ ! -z "$SHELL_CHECK_RESULT_DISK_SETUP" ]; then
              echo "The following are the warnings for disk setup script"
              echo "$SHELL_CHECK_RESULT_DISK_SETUP"
              fi
              if [ ! -z "$SHELL_CHECK_RESULT_IOT_SETUP" ]; then
              echo "The following are the warnings for iot setup script"
              echo "$SHELL_CHECK_RESULT_IOT_SETUP"
              fi
              if [ ! -z "$SHELL_CHECK_RESULT_DEPLOY_MODULES" ]; then
              echo "The following are the warnings for deploy modules script"
              echo "$SHELL_CHECK_RESULT_DEPLOY_MODULES"
              fi
              exit 1
          fi
        workingDirectory: '/home/vsts/work/1/s'
      
    - task: DownloadPipelineArtifact@2
      enabled: true
      displayName: 'Download artifacts from WebApp Build Pipeline'
      inputs:
        buildType: 'specific'
        project: '1ab7de3c-f8b7-4b59-be5a-fa78b4f4570c'
        definition: '6'
        buildVersionToDownload: 'latest'
        targetPath: '/home/vsts/work/1/s'

    - task: CopyFiles@2
      displayName: 'Copy deployment manifest files to a combined folder'
      inputs:
        SourceFolder: '/home/vsts/work/1/s/edge-solution/'
        Contents: |
          .env
          deployment.camera.template.json
        TargetFolder: '/home/vsts/work/1/s/edge-solution/combined'
    
    - task: CopyFiles@2
      displayName: 'Copy CameraStream module to a combined folder'
      inputs:
        SourceFolder: '/home/vsts/work/1/s/edge-solution/'
        Contents: |
          modules/CameraStream/module.json
        TargetFolder: '/home/vsts/work/1/s/edge-solution/combined/modules/CameraStream'
        flattenFolders: true

    - task: CopyFiles@2
      displayName: 'Copy Detector module to a combined folder'
      inputs:
        SourceFolder: '/home/vsts/work/1/s/edge-solution/'
        Contents: |
          modules/Detector/module.json
        TargetFolder: '/home/vsts/work/1/s/edge-solution/combined/modules/Detector'
        flattenFolders: true
    
    # Creating the manifest bundle zip from combined folder
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '/home/vsts/work/1/s/edge-solution/combined'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '/home/vsts/work/1/s/manifest-bundle.zip'
        replaceExistingArchive: true

    - task: CopyFiles@2
      displayName: 'Copy deployment manifest files to a combined folder'
      inputs:
        SourceFolder: '/home/vsts/work/1/s/'
        Contents: |
          manifest-bundle.zip
          ues_app/people-detection-app.zip
          deployment/arm/scripts/create-setup-iot-edge-device.sh
          deployment/arm/scripts/deploy-modules.sh
          deployment/arm/scripts/disk-setup.sh
          deployment/arm/azuredeploy.json
        TargetFolder: '/home/vsts/work/1/s/arm_template_bundle'
        flattenFolders: true



    # Creating the ARM Template deployment bundle zip.
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '/home/vsts/work/1/s/arm_template_bundle'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/arm-deployment-bundle.zip'
        replaceExistingArchive: true


    # Publishing the pipeline artifact
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)/arm-deployment-bundle.zip'
        artifact: 'arm-deployment-bundle'
        publishLocation: 'pipeline'
